version: '3.4'
services:
  splunk:
    image: amp4e/amp4e_splunk_events_input:latest
    build: .
    volumes:
      - .:/opt/splunk/etc/apps/amp4e_events_input
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - DEBUG=true
    ports:
      - "8000:8000"
    working_dir: /opt/splunk/etc/apps/amp4e_events_input
    
# Uncomment below for a clean container to use for testing
  # splunk-test:
  #   image: splunk/splunk:latest
  #   environment:
  #     - SPLUNK_START_ARGS=--accept-license
  #     - SPLUNK_PASSWORD=changeme
  #     - DEBUG=true
  #   ports:
  #     - "8001:8000"
  #   entrypoint: /sbin/entrypoint.sh
  #   command: start-service
