on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Dockerhub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: docker/setup-buildx-action@v1
      if: ${{ !env.ACT }}
    - name: build
      if: ${{ !env.ACT }}
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: amp4e/amp4e_splunk_events_input:latest
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker-compose -f docker-compose.ci.yml up -d
    - run: apt-get update -y && apt-get install -y python2.7 
    - run: pip install -r requirements.txt
    - name: wait for service
      uses: nev7n/wait_for_response@v1
      with:
        url: 'http://localhost:8000/'
        responseCode: 303
        timeout: 120000
        interval: 500
    - run: python -m unittest discover
    - name: cleanup
      if: ${{ always() }}
      run: docker-compose -f docker-compose.ci.yml down